version: 2.1

executors:
  node:
    parameters:
      nodeversion:
        type: string
        default: "11"
    docker:
      - image: circleci/node:<< parameters.nodeversion >>

jobs:
  test_libhoney:
    parameters:
      nodeversion:
        type: string
        default: "11"
    executor:
      name: node
      nodeversion: "<< parameters.nodeversion >>"
    steps:
      - checkout
      - run: npm ci
      - run: npm test

  publish:
    docker:
      - image: circleci/node:11.15.0-stretch
    steps:
      - checkout
      - run:
          name: store npm auth token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm ci
      - run: npm run lint
      - run: npm publish

workflows:
  build-libhoney:
    jobs:
      - test_libhoney:
          name: test_node891
          nodeversion: "8.9.1"
      - test_libhoney:
          name: test_node9
          nodeversion: "9"
      - test_libhoney:
          name: test_node1000
          nodeversion: "10.0.0"
      - test_libhoney:
          name: test_node10
          nodeversion: "10"
      - test_libhoney:
          name: test_node11
          nodeversion: "11"
      - publish:
          requires:
            - test_node891
            - test_node9
            - test_node1000
            - test_node10
            - test_node11
          filters:
              branches:
                only: master
              tags:
                only: /.+/
